name: Build android binary

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
            # Version range or exact version of a Python version to use, using SemVer's version range syntax.
            python-version: 3.7 # optional, default is 3.x
            # The target architecture (x86, x64) of the Python interpreter.
            architecture: x64 # optional
            # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
            #token: # optional, default is ${{ github.token }}
      # Runs a single command using the runners shell
      #- name: Install dependencies
      #  run: python3 -m pip install -r requirements.txt
      - name: List home and app directory
        run: |
          ls ~
          ls
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cp buildconfig/build_android.sh build_android.sh
          chmod +x build_android.sh # Just in case
          ./build_android.sh
      - name: List build files (debug)
        run: ls build/*
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
            name: android_package
            path: build/* # A file, directory or wildcard pattern that describes what to upload 
